import type { Config } from 'tailwindcss'

const config: Config = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#bac9cc",
        "border-subtle": "#334155",
        "surface-variant": "#2d3449",
        "inverse-on-surface": "#283044",
        "on-error-container": "#ffdad6",
        "surface-bright": "#31394d",
        "status-success": "#10B981",
        "on-error": "#690005",
        "on-background": "#dae2fd",
        "secondary-container": "#00a572",
        "background": "#0b1326",
        "secondary-fixed": "#6ffbbe",
        "outline-variant": "#3b494c",
        "primary-container": "#00e5ff",
        "on-secondary": "#003824",
        "on-surface": "#dae2fd",
        "code-cyan": "#22D3EE",
        "tertiary-fixed": "#e1e0ff",
        "surface-container-lowest": "#060e20",
        "surface-container-high": "#222a3d",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#004f58",
        "on-primary-fixed": "#001f24",
        "surface-tint": "#00daf3",
        "surface-container-highest": "#2d3449",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "tertiary-fixed-dim": "#c0c1ff",
        "primary-fixed-dim": "#00daf3",
        "surface": "#0b1326",
        "on-secondary-fixed-variant": "#005236",
        "surface-card": "#1E293B",
        "surface-container-low": "#131b2e",
        "surface-dim": "#0b1326",
        "secondary": "#4edea3",
        "on-secondary-fixed": "#002113",
        "inverse-surface": "#dae2fd",
        "on-primary-container": "#00626e",
        "primary": "#c3f5ff",
        "on-tertiary": "#1000a9",
        "tertiary-container": "#ccccff",
        "surface-container": "#171f33",
        "primary-fixed": "#9cf0ff",
        "inverse-primary": "#006875",
        "tertiary": "#edeaff",
        "error-container": "#93000a",
        "surface-deep": "#020617",
        "on-tertiary-container": "#4344d1",
        "on-primary": "#00363d",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#07006c",
        "outline": "#849396",
        "on-secondary-container": "#00311f",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        "margin-mobile": "16px",
        "section-gap": "80px",
        "container-max": "1200px",
        gutter: "24px",
      },
      fontFamily: {
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "display-lg-mobile": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "headline-md": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "headline-sm": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "label-md": ["var(--font-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "800" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.5", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      animation: {
        "pulse-dot": "pulseDot 2s infinite ease-in-out",
        pulse: "pulse 2s infinite",
      },
      keyframes: {
        pulseDot: {
          "0%": { transform: "scale(0.95)", opacity: "0.7" },
          "50%": { transform: "scale(1.05)", opacity: "1" },
          "100%": { transform: "scale(0.95)", opacity: "0.7" },
        },
        pulse: {
          "0%": { transform: "scale(0.95)", opacity: "0.8" },
          "50%": { transform: "scale(1.05)", opacity: "1" },
          "100%": { transform: "scale(0.95)", opacity: "0.8" },
        },
      },
    },
  },
  plugins: [],
}

export default config
